/**
 * Stable error codes — docs/architecture/04-command-model.md.
 *
 * Clients switch on `code`. They never parse `message`, which is for humans and
 * may be reworded freely. Codes are grouped by prefix so clients can handle
 * families.
 */

export const ERROR_CODES = {
  // Auth
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_DEVICE_NOT_REGISTERED: 'AUTH_DEVICE_NOT_REGISTERED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_UNSUPPORTED_COMBINATION: 'VALIDATION_UNSUPPORTED_COMBINATION',

  // Inventory
  INVENTORY_SEAT_UNAVAILABLE: 'INVENTORY_SEAT_UNAVAILABLE',
  INVENTORY_INSUFFICIENT_CAPACITY: 'INVENTORY_INSUFFICIENT_CAPACITY',
  INVENTORY_HOLD_EXPIRED: 'INVENTORY_HOLD_EXPIRED',
  INVENTORY_HOLD_NOT_FOUND: 'INVENTORY_HOLD_NOT_FOUND',
  INVENTORY_LIMIT_EXCEEDED: 'INVENTORY_LIMIT_EXCEEDED',
  INVENTORY_INVALID_TRANSITION: 'INVENTORY_INVALID_TRANSITION',
  INVENTORY_EXTEND_LIMIT_REACHED: 'INVENTORY_EXTEND_LIMIT_REACHED',
  INVENTORY_ALLOCATION_OVERLAP: 'INVENTORY_ALLOCATION_OVERLAP',

  // Event
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_NOT_ON_SALE: 'EVENT_NOT_ON_SALE',
  EVENT_INVALID_TRANSITION: 'EVENT_INVALID_TRANSITION',
  EVENT_NOT_PUBLISHABLE: 'EVENT_NOT_PUBLISHABLE',

  // Venue
  VENUE_NOT_FOUND: 'VENUE_NOT_FOUND',
  VENUE_INVALID_AREA_PARENT: 'VENUE_INVALID_AREA_PARENT',
  VENUE_DUPLICATE_CODE: 'VENUE_DUPLICATE_CODE',

  // Order
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  ORDER_EXPIRED: 'ORDER_EXPIRED',
  ORDER_INVALID_TRANSITION: 'ORDER_INVALID_TRANSITION',

  // Payment
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PROVIDER_UNAVAILABLE: 'PAYMENT_PROVIDER_UNAVAILABLE',
  PAYMENT_ALREADY_IN_FLIGHT: 'PAYMENT_ALREADY_IN_FLIGHT',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_INVALID_TRANSITION: 'PAYMENT_INVALID_TRANSITION',
  PAYMENT_CALLBACK_UNVERIFIED: 'PAYMENT_CALLBACK_UNVERIFIED',

  // Ticket
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_ALREADY_USED: 'TICKET_ALREADY_USED',
  TICKET_VOID: 'TICKET_VOID',
  TICKET_NOT_YOURS: 'TICKET_NOT_YOURS',
  TICKET_INVALID_TRANSITION: 'TICKET_INVALID_TRANSITION',

  // Transfer
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  TRANSFER_NOT_ALLOWED: 'TRANSFER_NOT_ALLOWED',
  TRANSFER_ALREADY_PENDING: 'TRANSFER_ALREADY_PENDING',
  TRANSFER_ALREADY_ACCEPTED: 'TRANSFER_ALREADY_ACCEPTED',
  TRANSFER_CANCELLED: 'TRANSFER_CANCELLED',
  TRANSFER_EXPIRED: 'TRANSFER_EXPIRED',
  TRANSFER_CUTOFF_PASSED: 'TRANSFER_CUTOFF_PASSED',
  TRANSFER_SELF_NOT_ALLOWED: 'TRANSFER_SELF_NOT_ALLOWED',
  TRANSFER_REFUND_BLOCKED: 'TRANSFER_REFUND_BLOCKED',
  TRANSFER_RECIPIENT_MISMATCH: 'TRANSFER_RECIPIENT_MISMATCH',

  // Admission — one code per reason, because a gate operator needs to know WHY
  // someone is being turned away. "Already used at Gate 3 at 14:02" is
  // actionable; "invalid" is not.
  ADMISSION_DENIED_ALREADY_USED: 'ADMISSION_DENIED_ALREADY_USED',
  ADMISSION_DENIED_NOT_PAID: 'ADMISSION_DENIED_NOT_PAID',
  ADMISSION_DENIED_REFUNDED: 'ADMISSION_DENIED_REFUNDED',
  ADMISSION_DENIED_VOID: 'ADMISSION_DENIED_VOID',
  ADMISSION_DENIED_EXPIRED: 'ADMISSION_DENIED_EXPIRED',
  ADMISSION_DENIED_WRONG_EVENT: 'ADMISSION_DENIED_WRONG_EVENT',
  ADMISSION_DENIED_WRONG_GATE: 'ADMISSION_DENIED_WRONG_GATE',
  ADMISSION_DENIED_OUTSIDE_WINDOW: 'ADMISSION_DENIED_OUTSIDE_WINDOW',
  ADMISSION_DENIED_EVENT_NOT_ACTIVE: 'ADMISSION_DENIED_EVENT_NOT_ACTIVE',
  ADMISSION_DENIED_UNKNOWN_CREDENTIAL: 'ADMISSION_DENIED_UNKNOWN_CREDENTIAL',
  ADMISSION_DENIED_CREDENTIAL_REVOKED: 'ADMISSION_DENIED_CREDENTIAL_REVOKED',
  ADMISSION_DENIED_GATE_NOT_AUTHORIZED: 'ADMISSION_DENIED_GATE_NOT_AUTHORIZED',
  ADMISSION_DENIED_MALFORMED_CREDENTIAL: 'ADMISSION_DENIED_MALFORMED_CREDENTIAL',

  // Fees and finance
  FEE_SCHEDULE_NOT_FOUND: 'FEE_SCHEDULE_NOT_FOUND',
  FEE_CALCULATION_FAILED: 'FEE_CALCULATION_FAILED',
  SETTLEMENT_INVALID_PERIOD: 'SETTLEMENT_INVALID_PERIOD',

  // System
  SYSTEM_UNAVAILABLE: 'SYSTEM_UNAVAILABLE',
  SYSTEM_RATE_LIMITED: 'SYSTEM_RATE_LIMITED',
  SYSTEM_RETRY_IN_PROGRESS: 'SYSTEM_RETRY_IN_PROGRESS',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * Codes a client may sensibly retry. Everything else needs a different action,
 * not a repeat of the same one.
 */
export const RETRYABLE_ERROR_CODES: readonly ErrorCode[] = [
  ERROR_CODES.SYSTEM_UNAVAILABLE,
  ERROR_CODES.SYSTEM_RATE_LIMITED,
  ERROR_CODES.SYSTEM_RETRY_IN_PROGRESS,
  ERROR_CODES.PAYMENT_PROVIDER_UNAVAILABLE,
];

export function isRetryable(code: ErrorCode): boolean {
  return RETRYABLE_ERROR_CODES.includes(code);
}

/**
 * Operator-facing text for a denied scan. The gate app renders these verbatim;
 * dynamic detail (gate name, time) is appended by the app from the response.
 */
export const ADMISSION_DENIAL_TEXT: Readonly<Record<string, string>> = {
  ADMISSION_DENIED_ALREADY_USED: 'Already admitted',
  ADMISSION_DENIED_NOT_PAID: 'Payment not completed',
  ADMISSION_DENIED_REFUNDED: 'This ticket was refunded',
  ADMISSION_DENIED_VOID: 'This ticket was cancelled',
  ADMISSION_DENIED_EXPIRED: 'This ticket has expired',
  ADMISSION_DENIED_WRONG_EVENT: 'This ticket is for a different event',
  ADMISSION_DENIED_WRONG_GATE: 'Wrong gate',
  ADMISSION_DENIED_OUTSIDE_WINDOW: 'Gates are not open',
  ADMISSION_DENIED_EVENT_NOT_ACTIVE: 'This event is not active',
  ADMISSION_DENIED_UNKNOWN_CREDENTIAL: 'Ticket not recognised',
  ADMISSION_DENIED_CREDENTIAL_REVOKED: 'This ticket was transferred — ask for the new QR code',
  ADMISSION_DENIED_GATE_NOT_AUTHORIZED: 'This device is not authorised for this event',
  ADMISSION_DENIED_MALFORMED_CREDENTIAL: 'Ticket not recognised',
};
